FROM docker:stable

# Installing c-ares (1.15.0-r0)
# Installing libgcc (9.2.0-r4)
# Installing nghttp2-libs (1.40.0-r0)
# Installing libstdc++ (9.2.0-r4)
# Installing libuv (1.34.0-r0)
# Installing nodejs (12.15.0-r1)
# Installing npm (12.15.0-r1)
RUN apk add --update nodejs npm
